### ISSUE TITLE
관련 컨트롤러 통일화 (추후 개발시)

### ISSUE THREAD

**Issue by digitalRepresentation** [digitalRepresentation/recipe-osusume#19]
레시피 등록(수정,삭제 포함), 상세정보와 같은 화면도 같은 컨트롤러에서 구현하는 게 어떨까요
지금은 제가 따로 레시피 등록 컨트롤러(RecipeCreateController) 만들어서 하고 있는데
레시피 컨트롤러(RecipeController)안에서 따로 구현해도 괜찮을 듯 합니다

**Comment by ddanya6327** [comment]
레시피 관련은 레시피 컨트롤러에
new, show, edit, delete 같은 형태로 구현하면 될 듯
